# docker-compose.yml for gateway service
version: "3.7"
services:
  gateway:
    container_name: gateway
    image: gateway
    restart: always
    build:
      context: ./gateway
      dockerfile: Dockerfile
    env_file:
      - ./gateway/.env
    ports:
      - "5000:5000"
  service-a:
    container_name: service-a
    image: service-a
    restart: always
    build:
      context: ./serviceA
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
